apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template: # 起動する Pod の設定テンプレート
    metadata:
      # kubectl コマンドや Service などから Pod を参照する際にこのラベルを使って絞り込むことができる
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gcr.io/market-sample/nginx-example:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /share
              name: share-volume
        - name: rails
          image: gcr.io/market-sample/rails-example:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-settings
                  key: pghost
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-user
                  key: pguser
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-password
                  key: pgpassword
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-database
                  key: pgdatabase
          volumeMounts:
            - mountPath: /share
              name: share-volume
          command: ["unicorn", "-p", "3000", "-c", "/app/config/unicorn.rb"]
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=market-sample:asia-northeast1:market=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: share-volume
          emptyDir: {}
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
