apiVersion: batch/v1
kind: Job
metadata:
  name: rails-batch
spec:
  template:
    spec:
      containers:
        - name: rails-batch
          image: gcr.io/app-cluster-196205/rails-example:v6
          imagePullPolicy: Always
          command: ["bin/rails", "search_index:fetch"]
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-host
                  key: pghost
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-user
                  key: pguser
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-password
                  key: pgpassword
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pg-database
                  key: pgdatabase
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-redis-host
                  key: redishost
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: cloudsql-redis-port
                  key: redisport
            - name: ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-elasticsearch-host
                  key: elasticsearchhost
            - name: ELASTICSEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: cloudsql-elasticsearch-port
                  key: elasticsearchport
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.09
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=app-cluster-196205:asia-northeast1:sample-db=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      restartPolicy: Never
  backoffLimit: 1
