steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/market-sample/rails-example', '--build-arg', 'RAILS_ENV_ARG=production', '--build-arg', 'SECRET_KEY_BASE_ARG=$SECRETE_BASE', '--build-arg', 'BUNDLE_GEMFILE_ARG=/app/omochi/Gemfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/market-sample/rails-example']
