version: '2'
services:
  elasticsearch:
    build: es
    volumes:
        - es-data:/usr/share/elasticsearch/data
        - ./es/config:/usr/share/elasticsearch/config
    ports:
        - 9200:9200
        - 9300:9300
    expose:
        - 9300
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "http.host=0.0.0.0"
        - "transport.host=127.0.0.1"
        - "xpack.security.enabled=false"
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
        # https://github.com/docker-library/elasticsearch/issues/111
        # uliimit
  # kibana:
  #   build: kibana
  #   links:
  #       - elasticsearch:elasticsearch
  #   ports:
  #       - 5601:5601
volumes:
    es-data:
        driver: local
